import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity, ScrollView, ActivityIndicator, Alert } from 'react-native';
import { balanceTeams } from '../utils/teamBalancer';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import AsyncStorage from '@react-native-async-storage/async-storage';
// 1. Import Clipboard
import * as Clipboard from 'expo-clipboard';

export default function ResultScreen({ route, navigation }) {
  const { players, currentUser } = route.params; 
  const [result, setResult] = useState(null);

  useEffect(() => {
    const balancedData = balanceTeams(players);
    setResult(balancedData);
  }, [players]);

  const handleFinish = async () => {
    try {
      const currentCount = await AsyncStorage.getItem('matchesPlayed');
      let count = currentCount ? parseInt(currentCount) : 0;
      count += 1;
      await AsyncStorage.setItem('matchesPlayed', count.toString());

      const historyItem = {
        id: Date.now().toString(),
        date: new Date().toLocaleDateString() + ' ' + new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        teamA: result.teamA,
        teamB: result.teamB,
        scoreA: result.scoreA,
        scoreB: result.scoreB,
        bench: result.bench
      };

      const existingHistory = await AsyncStorage.getItem('matchHistory');
      const historyList = existingHistory ? JSON.parse(existingHistory) : [];
      await AsyncStorage.setItem('matchHistory', JSON.stringify([historyItem, ...historyList]));

    } catch (error) {
      console.log("Error saving history", error);
    }
    navigation.navigate('Home');
  };

  // --- 2. NEW COPY FUNCTION ---
  const copyToClipboard = async () => {
    if (!result) return;

    // Create a nice text format for WhatsApp
    let text = `🏆 MATCH TEAMS 🏆\n\n`;
    
    text += `🟢 TEAM A (Skill: ${result.scoreA})\n`;
    result.teamA.forEach(p => text += `• ${p.name} (${p.score})\n`);
    
    text += `\n🔵 TEAM B (Skill: ${result.scoreB})\n`;
    result.teamB.forEach(p => text += `• ${p.name} (${p.score})\n`);

    if (result.bench.length > 0) {
        text += `\n⚠️ BENCH\n`;
        result.bench.forEach(p => text += `• ${p.name}\n`);
    }

    text += `\n- Generated by Match Mixer`;

    await Clipboard.setStringAsync(text);
    Alert.alert("Copied!", "Team list copied to clipboard.\nPaste it in WhatsApp!");
  };

  if (!result) return (
    <View style={styles.loadingContainer}>
      <ActivityIndicator size="large" color="#3b5998" />
      <Text style={{marginTop: 10, color: '#666'}}>Calculating Teams...</Text>
    </View>
  );

  const renderPlayer = ({ item }) => (
    <View style={styles.playerRow}>
        <View style={{flexDirection: 'row', alignItems: 'center'}}>
            <Ionicons name="person-circle" size={30} color="#555" style={{marginRight: 8}} />
            <Text style={[
                styles.name, 
                item.name === currentUser && styles.meText 
            ]}>
                {item.name} {item.name === currentUser && "(You)"}
            </Text>
        </View>
        <Text style={styles.score}>{item.score}</Text>
    </View>
  );

  const amIOnBench = result.bench.some(p => p.name === currentUser);

  return (
    <LinearGradient
      colors={['#4c669f', '#3b5998', '#192f6a']} 
      style={styles.container}
    >
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Match Ready</Text>
        <Text style={styles.headerSub}>Teams have been balanced.</Text>
      </View>

      <ScrollView style={styles.scrollContainer} contentContainerStyle={{ paddingBottom: 120 }}>
        
        <View style={styles.teamsWrapper}>
            {/* Team A */}
            <View style={styles.teamCard}>
                <View style={[styles.cardHeader, { backgroundColor: '#4CAF50' }]}>
                    <Text style={styles.teamName}>Team A</Text>
                    <Text style={styles.totalScore}>Total: {result.scoreA}</Text>
                </View>
                <FlatList data={result.teamA} renderItem={renderPlayer} scrollEnabled={false} />
            </View>

            {/* VS */}
            <View style={styles.vsBadge}><Text style={styles.vsText}>VS</Text></View>

            {/* Team B */}
            <View style={styles.teamCard}>
                <View style={[styles.cardHeader, { backgroundColor: '#2196F3' }]}>
                    <Text style={styles.teamName}>Team B</Text>
                    <Text style={styles.totalScore}>Total: {result.scoreB}</Text>
                </View>
                <FlatList data={result.teamB} renderItem={renderPlayer} scrollEnabled={false} />
            </View>
        </View>

        {/* Bench */}
        {result.bench.length > 0 && (
          <View style={styles.benchCard}>
            <View style={styles.benchHeaderRow}>
                <Ionicons name="warning" size={24} color="#F57C00" />
                <Text style={styles.benchTitle}>Standby Player</Text>
            </View>
            <View style={styles.benchContent}>
                {amIOnBench ? (
                    <Text style={styles.benchMsg}><Text style={{ fontWeight: 'bold' }}>Action Required:</Text> You need one more member!</Text>
                ) : (
                    <Text style={styles.benchMsg}><Text style={{fontWeight:'bold'}}>{result.bench[0].name}</Text> is not selected.</Text>
                )}
                <FlatList data={result.bench} renderItem={renderPlayer} scrollEnabled={false} />
            </View>
          </View>
        )}

      </ScrollView>

      {/* --- FOOTER BUTTONS --- */}
      <View style={styles.footer}>
        <View style={styles.btnRow}>
            
            {/* 3. NEW COPY BUTTON */}
            <TouchableOpacity style={styles.copyBtn} onPress={copyToClipboard}>
                <Ionicons name="copy-outline" size={20} color="white" />
                <Text style={styles.copyText}>Copy</Text>
            </TouchableOpacity>

            {/* Existing Finish Button */}
            <TouchableOpacity style={styles.homeBtn} onPress={handleFinish}>
                <Ionicons name="home" size={20} color="#333" style={{marginRight: 10}} />
                <Text style={styles.btnText}>Finish</Text>
            </TouchableOpacity>

        </View>
      </View>

    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { paddingTop: 60, paddingBottom: 20, alignItems: 'center' },
  headerTitle: { fontSize: 32, fontWeight: 'bold', color: 'white' },
  headerSub: { fontSize: 16, color: '#ccddee' },
  scrollContainer: { flex: 1, paddingHorizontal: 20 },
  teamsWrapper: { gap: 20, marginTop: 10 },
  teamCard: { backgroundColor: 'white', borderRadius: 16, overflow: 'hidden', elevation: 5 },
  cardHeader: { padding: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  teamName: { fontSize: 20, fontWeight: 'bold', color: 'white' },
  totalScore: { color: 'rgba(255,255,255,0.9)', fontWeight: '600' },
  vsBadge: { alignSelf: 'center', backgroundColor: 'white', width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginVertical: -10, zIndex: 10, elevation: 6, borderWidth: 2, borderColor: '#eee' },
  vsText: { fontWeight: '900', color: '#999', fontSize: 12 },
  playerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 15, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  name: { fontSize: 16, color: '#333' },
  meText: { fontWeight: 'bold', color: '#4CAF50' },
  score: { fontWeight: 'bold', color: '#888' },
  benchCard: { marginTop: 30, backgroundColor: '#FFF3E0', borderRadius: 12, borderWidth: 1, borderColor: '#FFE0B2', overflow: 'hidden' },
  benchHeaderRow: { flexDirection: 'row', alignItems: 'center', padding: 10, backgroundColor: '#FFE0B2' },
  benchTitle: { fontSize: 16, fontWeight: 'bold', color: '#E65100', marginLeft: 10 },
  benchContent: { padding: 15 },
  benchMsg: { color: '#E65100', marginBottom: 10, lineHeight: 20 },
  
  // Footer Styles
  footer: { position: 'absolute', bottom: 30, left: 20, right: 20 },
  btnRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 15 },
  
  // Copy Button
  copyBtn: { 
      flex: 1, 
      backgroundColor: '#607D8B', 
      padding: 18, 
      borderRadius: 15, 
      alignItems: 'center', 
      flexDirection: 'row', 
      justifyContent: 'center',
      elevation: 5 
  },
  copyText: { color: 'white', fontWeight: 'bold', marginLeft: 8 },

  // Home Button
  homeBtn: { 
      flex: 2, // Bigger than copy button
      backgroundColor: 'white', 
      padding: 18, 
      borderRadius: 15, 
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      elevation: 5
  },
  btnText: { color: '#333', fontSize: 16, fontWeight: 'bold' }
});